## Sample configuration- GET request
#[request]
## Use the GET request method
#method = "GET"
## Set the URL targets. Any valid URL is accepted, including ports, https, and parameters. Must be an array.
#targets = ["http://www.example.com/account/update?email=you@example.com","http://www.example.com/account/update?email=me@example.com"]
## Set the cookie values to send with the request. Must be an array.
#cookies = ["PHPSESSIONID=12345","JSESSIONID=67890"]
## Follow redirects
#redirects = true
## Send 100 requests to each target
#count = 100
## Enable verbose logging
#verbose = true

## Sample Configuration- POST request
#[request]
## Use the POST request method
#method = "POST"
## Set the URL target. Any valid URL is accepted, including ports, https, and parameters. Must be an array.
#targets = ["http://www.example.com/account/update"]
## Set the request body.
#body = "email=you@example.com&email=me@example.com"
## Set the cookie values to send with the request. Must be an array.
#cookies = ["PHPSESSIONID=12345","JSESSIONID=67890"]
## Follow redirects
#redirects = true
## Send 100 requests to the target
#count = 100
## Enable verbose logging
#verbose = true